### PR TITLE
Fix deprecations in HomeAssistant 2025.1, 2025.5 & 2025.6

### LINKED ISSUE #31: POWER_WATT and other used constants will be deprecated by HA Core 2025.1
I get deprecated constant warnings in my kostal logs.

`Logger: homeassistant.const
Quelle: helpers/deprecation.py:206
Erstmals aufgetreten: 16:31:21 (6 Vorkommnisse)
Zuletzt protokolliert: 16:31:30

POWER_WATT was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'kostal' custom integration
ENERGY_KILO_WATT_HOUR was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'kostal' custom integration
ELECTRIC_POTENTIAL_VOLT was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please report it to the author of the 'kostal' custom integration
ELECTRIC_CURRENT_AMPERE was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead, please report it to the author of the 'kostal' custom integration
DEVICE_CLASS_ENERGY was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please report it to the author of the 'kostal' custom integration

Logger: homeassistant.components.sensor
Quelle: helpers/deprecation.py:206
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 16:31:30 (4 Vorkommnisse)
Zuletzt protokolliert: 16:31:30

STATE_CLASS_MEASUREMENT was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please report it to the author of the 'kostal' custom integration
STATE_CLASS_TOTAL_INCREASING was used from kostal, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please report it to the author of the 'kostal' custom integration`

### PR DESCRIPTION
**Pull request by m-rossi**
This PR fixes a bunch of deprecations in HomeAssistant of the coming releases, some named in #31 and similar to #29, but a lot less changes. So I am hoping to have a quick review @rcasula.

I tested this PR with my own Piko 8.3 and during setup, execution and deletion of the integration I see no errors and deprecation warnings.

Close #31

### CODE REVIEW

**Comment by mystal007** [comment]
Hi @m-rossi 
Thanks for the update, however after updating HA to 2025.1, I cannot get it to work. I have tried to remove the integration and installed again in HACS and using beta v. 3.0.1.
I get the following message when trying to add it from integration:

ERROR
Config flow could not be loaded: {"message":"Invalid handler specified"}

Please let me know if how to get it to work again, thx

**Comment by m-rossi** [comment]
Oh that's bad. I have tested it against the development version during that time (2024.12) and it worked. I have not updated to 2025.1 myself. I will look into it later today.

**Comment by mystal007** [comment]
It worked in my 2024.12 as well. But it stopped working with a red box around the integration after 2025.1 update. Thats why I removed it and tried adding it again.

I can see 2025.1.1 is out now, I will test with that version as well.

**Comment by mystal007** [comment]
I just tested 2025.1.1 and same error..
It just quickly says "Starting configuration wizard"
and then throw this error:
image

**Comment by m-rossi** [comment]
I just did a quick test in my development environment and added my Kostal and everything seems to work as expected. May you can have another look in your logs and [open a separate issue](https://github.com/rcasula/kostalpiko-homeassistant/issues)? I will wait with the update of my production-homeassistant a few more days.

**Pull request merged**
